# 002_pytorch_creation_ops

In [2]:
# Install pytorch if not alreaady available
!pip install torch

    100% |████████████████████████████████| 519.5MB 33kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x5a39c000 @  0x7fe07e84f2a4 0x594e17 0x626104 0x51190a 0x4f5277 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x4f3338 0x510fb0 0x5119bd 0x4f6070


In [0]:
# Essential imports
import torch
import numpy as np

In [7]:
# torch.tensor
# Paramters -> data, dtype, device, requires_grad

t1 = torch.tensor([1., 2., 3., 4., 5.],
                  dtype=torch.float32,
                  device=None,
                  requires_grad=False)

t2 = torch.tensor([[1., 2.], [3., 4.], [5., 6.]],
                  dtype=torch.float64,
                  device=torch.device('cpu:0'),
                  requires_grad=False)

t3 = torch.tensor([])

print ('1D Tensor - t1: ', t1)
print ('2D Tensor - t2: ', t2)
print ('Empty Tensor - t3: ', t3)

1D Tensor - t1:  tensor([1., 2., 3., 4., 5.])
2D Tensor - t2:  tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)
Empty Tensor - t3:  tensor([])


In [9]:
# torch.sparse_coo_tensor
# Parameters -> indices, values, size, dtype, device ,requires_grad

indices = torch.LongTensor([[0, 1, 1],
                            [2, 0, 2]])

values = torch.FloatTensor([3, 4, 5])

sct1 = torch.sparse_coo_tensor(indices, values, torch.Size([2, 4]))

print ('Sparse coo tensor: ', sct1)

Sparse coo tensor:  torch.sparse.FloatTensor of size (2,4) with indices:
tensor([[0, 1, 1],
        [2, 0, 2]])
and values:
tensor([3., 4., 5.])


In [13]:
# torch.as_tensor(data, dtype=None, device=None)

data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
t1 = torch.as_tensor(data, dtype=torch.float32)

np_data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
t2 = torch.as_tensor(np_data, dtype=torch.float32)

print('t1 tensor from data: ', t1, ' with type ', type(t1))
print('t2 tensor from np_data: ', t2, ' with type ', type(t1))

t1 tensor from data:  tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])  with type  <class 'torch.Tensor'>
t2 tensor from np_data:  tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])  with type  <class 'torch.Tensor'>


In [15]:
# torch.from_numpy(ndarray)

np_data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
t2 = torch.from_numpy(np_data)

print('t1 tensor from np_data: ', t1, ' with type ', type(t1))

t1 tensor from np_data:  tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])  with type  <class 'torch.Tensor'>


In [17]:
# torch.zeros(*sizes, out, dtype, layout, device, requires_grad)

z1 = torch.zeros(2, 3)
z2 = torch.zeros(3, 2, 2)

print('2D Zero Tensor: ', z1)
print('3D Zero Tensor: ', z2)

2D Zero Tensor:  tensor([[0., 0., 0.],
        [0., 0., 0.]])
3D Zero Tensor:  tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


In [20]:
# torch.zeros_like(input, dtype=None, layout=None, device=None, requires_grad=False) → Tensor

d1 = torch.as_tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tzl1 = torch.zeros_like(d1)

d2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
tzl2 = torch.zeros_like(torch.as_tensor(d2))

print('tzl1 has d1 shaped zeros: ', tzl1)
print('tzl2 has d2 shaped zeros: ', tzl2)

tzl1 has d1 shaped zeros:  tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tzl2 has d2 shaped zeros:  tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [27]:
# torch.ones(*sizes, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

tzl1 = torch.ones(4, 3)
tzl2 = torch.ones(2, 3)

print('tzl1 has d1 shaped ones: ', tzl1)
print('tzl2 has d2 shaped ones: ', tzl2)

tzl1 has d1 shaped ones:  tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tzl2 has d2 shaped ones:  tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [29]:
# torch.ones_like(input, dtype=None, layout=None, device=None, requires_grad=False) → Tensor

d1 = torch.as_tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tzl1 = torch.ones_like(d1)

d2 = [[1, 2, 3], [7, 8, 9]]
tzl2 = torch.ones_like(torch.as_tensor(d2))

print ('tzl1: ', tzl1)
print('tzl2 has d2 shaped ones: ', tzl2)

tzl1:  tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tzl2 has d2 shaped ones:  tensor([[1, 1, 1],
        [1, 1, 1]])


In [32]:
# torch.arange(start=0, end, step=1, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

t1 = torch.arange(5)
t2 = torch.arange(2, 10, 2)

print('t1: ', t1)
print('t2: ', t2)

t1:  tensor([0, 1, 2, 3, 4])
t2:  tensor([2, 4, 6, 8])


In [33]:
# torch.linspace(start, end, steps=100, out=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

t1 = torch.linspace(12, 28, steps=7)
t2 = torch.linspace(5, 45, steps=9)

print ('t1: ', t1)
print ('t2: ', t2)

t1:  tensor([12.0000, 14.6667, 17.3333, 20.0000, 22.6667, 25.3333, 28.0000])
t2:  tensor([ 5., 10., 15., 20., 25., 30., 35., 40., 45.])


In [34]:
# torch.logspace(start, end, steps=100, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

t1 = torch.logspace(start=-10, end=5, steps=6)
t2 = torch.logspace(start=0.34, end=3.56, steps=8)

print ('t1: ', t1)
print ('t2: ', t2)

t1:  tensor([1.0000e-10, 1.0000e-07, 1.0000e-04, 1.0000e-01, 1.0000e+02, 1.0000e+05])
t2:  tensor([   2.1878,    6.3096,   18.1970,   52.4808,  151.3562,  436.5157,
        1258.9252, 3630.7800])


In [36]:
# torch.eye(n, m=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

t1 = torch.eye(3)
t2 = torch.eye(1)

print ('Identity Matrix t1: \n', t1)
print ('Identity Matrix t2: \n', t2)

Identity Matrix t1: 
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Identity Matrix t2: 
 tensor([[1.]])


In [37]:
# torch.empty(*sizes, out=None, dtype=None, layout=torch.strided, device=None, requries_grad=False) -> Tensor

t1 = torch.empty(2, 3)
t2 = torch.empty(3, 2, 2)

print ('Empty tensor t1: ', t1)
print ('Empty tensor t2: ', t2)

Empty tensor t1:  tensor([[4.8051e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.0000e+05]])
Empty tensor t2:  tensor([[[0.0000, 0.0000],
         [0.0000, 0.0000]],

        [[0.0000, 0.0000],
         [0.0000, 0.0000]],

        [[0.0000, 0.0000],
         [0.0000, 0.0000]]])


In [39]:
# torch.empty_like(input, dtype=None, layout=None, device=None, requries_grad=False) -> Tensor

d1 = torch.tensor([1, 2, 3, 4, 5])
t1 = torch.empty_like(d1)

d2 = np.array([[1, 2], [3, 4]])
t2 = torch.empty_like(torch.from_numpy(d2))

print ('t1: ', t1)
print ('t2: ', t2)

t1:  tensor([44889728, 89581488,        0, 80425448, 80426288])
t2:  tensor([[       80505504,               0],
        [     4294967295, 125823003551060]])


In [40]:
# torch.full(size, fill_value, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

t1 = torch.full((2, 3), 9.45)
t2 = torch.full((4, 3, 2), 45.2)

print ('full tensor with 9.45: \n', t1)
print ('full tensor with 45.2: \n', t2)

full tensor with 9.45: 
 tensor([[9.4500, 9.4500, 9.4500],
        [9.4500, 9.4500, 9.4500]])
full tensor with 45.2: 
 tensor([[[45.2000, 45.2000],
         [45.2000, 45.2000],
         [45.2000, 45.2000]],

        [[45.2000, 45.2000],
         [45.2000, 45.2000],
         [45.2000, 45.2000]],

        [[45.2000, 45.2000],
         [45.2000, 45.2000],
         [45.2000, 45.2000]],

        [[45.2000, 45.2000],
         [45.2000, 45.2000],
         [45.2000, 45.2000]]])


In [41]:
# torch.full_like(input, fill_value, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

d1 = torch.tensor([1, 4, 65, 12, 78])
t1 = torch.full_like(d1, 90)

d2 = [[34, 12], [78, 23], [89, 12]]
t1 = torch.full_like(torch.tensor(d2), 78.3)

print ('Tensor filled with 90: ', t1)
print ('Tensor filled with 78.3: ', t2)

Tensor filled with 90:  tensor([[78, 78],
        [78, 78],
        [78, 78]])
Tensor filled with 78.3:  tensor([[[45.2000, 45.2000],
         [45.2000, 45.2000],
         [45.2000, 45.2000]],

        [[45.2000, 45.2000],
         [45.2000, 45.2000],
         [45.2000, 45.2000]],

        [[45.2000, 45.2000],
         [45.2000, 45.2000],
         [45.2000, 45.2000]],

        [[45.2000, 45.2000],
         [45.2000, 45.2000],
         [45.2000, 45.2000]]])
